# Backend configuration
# https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.name }}-app-backend
  namespace: {{ .Values.namespace }}
spec:
  timeoutSec: 120
  healthCheck:
    checkIntervalSec: 10
    port: 8000
    type: HTTP
    requestPath: /api/health/check