---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.name }}-app-configs
    namespace: {{ .Values.namespace }}
data:
    REDIS_URL: {{ template "redisUrl" . }}
    RABBITMQ_DEFAULT_USER: {{ .Values.database.rabbitmq.user | quote }}