# https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling#kubectl-apply
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ .Values.name }}-orders-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}-orders
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  