apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}-app-secrets
    namespace: {{ .Values.namespace }}
data:
    RABBITMQ_DEFAULT_PASS: {{ .Values.database.rabbitmq.password | b64enc | quote }}
    DATABASE_URL: {{ template "postgresUrl" . }}