apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}-rabbitmq-secrets
    namespace: {{ .Values.namespace }}
data:
    RABBITMQ_ERLANG_COOKIE: {{ .Values.database.rabbitmq.cookie | b64enc | quote }}
    