apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name:  {{ .Values.name }}-orders-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: "{\"default\": \"{{ .Values.name }}-app-backend\"}"
spec:
  selector:
    app:  {{ .Values.name }}-orders
  ports:
  - name: orders-port
    port: 8000
    protocol: TCP