apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-rabbitmq
spec:
  replicas: 1
  serviceName: {{ .Values.name }}-rabbitmq
  selector:
    matchLabels:
      app: {{ .Values.name }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.docker.image.rabbitmq }}
        resources:
          requests:
            memory: 0.5Gi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 600m
        envFrom:
        - secretRef:
            name: {{ .Values.name }}-rabbitmq-secrets
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi